### ISSUE TITLE
Error in captureSuccess : E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 3686704) 

### ISSUE THREAD

**Issue by Paul75** [CJT2325/CameraView#106]
Hello,

I do this :
`public void captureSuccess(Bitmap bitmap) {
                Log.i("JCameraView", "bitmap = " + bitmap.getWidth());
                Intent returnIntent = new Intent();
                returnIntent.putExtra("result",bitmap);
                returnIntent.putExtra("pneu",pneuChoice);
                setResult(Activity.RESULT_OK,returnIntent);
                JCameraViewActivity.this.finish();
            }`
 
to return in my activity result the bitmap. But I have in a  console :
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 3686704)

Why ?

**Comment by Paul75** [comment]
you don't know ?

**Comment by CJT2325** [comment]
Intent cannot transfer large data ...

**Comment by Paul75** [comment]
but with the demo of cameraview of google it not pose problem to transfert the image ?

**Comment by CJT2325** [comment]
you just need to save the Bitmap as file and transfer the url of the file by Intent

**Comment by CJT2325** [comment]
url of the file  or   url of one ? Which is better?  haha~

**Comment by Paul75** [comment]
Thanks for help
