### ISSUE TITLE
录制完毕 回调慢了 不知道各位有没有遇到过 

### ISSUE THREAD

**Issue by 932236581** [CJT2325/CameraView#107]
就是我录制5秒这样    finish 之后 onActivityResult  过了3-5秒 才响应

**Comment by dom4j1** [comment]
遇见过  修改JCameraView的移除代码 有所改善 但是还是达不到微信的反应速度  这个也受手机性能影响  不同手机响应速度不一样 改完之后 产品表示可以接受 就没有继续深究
