### ISSUE TITLE
app module 中的示例代码有问题

### ISSUE THREAD

**Issue by shaonialife** [CJT2325/CameraView#121]
在 getPermissions() 中判断了 是否是否大于等于 API23 ，但是没有写else，导致在 6.0 以下 granted 一直为 false，在 Activity.onResume() 中 就不会走 jCameraView.onResume();，也就不会注册 SensorEventListener 来监听旋转，导致横屏时拍摄的视频角度是错的

**Comment by CJT2325** [comment]
不要用app model这个   用cameraapplication这个

**Comment by shaonialife** [comment]
当时就想简单的复制粘贴，没注意这个，但是代码确实有问题

**Comment by tancolo** [comment]
@CJT2325 既然有问题，而且还是Android 默认的app目录，难免那个猛汉子，直接就看app 导致出现问题。
何不 删除app目录？ 不知道CJT 你是怎么考量的？
