### ISSUE TITLE
授权成功后黑屏

### ISSUE THREAD

**Issue by ytsxg123** [CJT2325/CameraView#133]
相机权限授权成功后，调用onResume方法，视频画面为黑色。手机，华为CAZ-AL10

**Comment by chenjunyubt** [comment]
解决了吗？ 同样遇到 允许所有权限后， 一直停留黑屏，  只有退出后再进 才能预览相机...   ; 这个怎么解决

**Comment by TJundx** [comment]
vivo，三星S8依赖后，黑屏
