### ISSUE TITLE
右键的监听没有回调啊

### ISSUE THREAD

**Issue by shanchainzj** [CJT2325/CameraView#136]
点击右键没有反应

**Comment by zkjmyy** [comment]
同楼上，如何解决？

**Comment by zkjmyy** [comment]
@Override
            public void recordSuccess(String url, Bitmap firstFrame) {
                //获取视频路径
                finish();//这个接口中是可以关闭；
            }


//该接口不是拍完照的绿色对勾的回调
 jCameraView.setRightClickListener(new ClickListener() {
            @Override
            public void onClick() {
                Toast.makeText(CameraActivity.this,"Right",Toast.LENGTH_SHORT).show();
            }
        });
