### ISSUE TITLE
播放视频崩溃

### ISSUE THREAD

**Issue by zhupengxiang** [CJT2325/CameraView#137]
我想复制playvideo代码   用于预览视频 mMediaPlayer.setSurface(mVideoView.getHolder().getSurface());
一直报错 The surface has been released 能帮忙看看么

**Comment by dom4j1** [comment]
如果只是想要视频预览效果 完全可以使用Mediaplayer+TextureView 的方式来播放 你遇见的这个问题是因为VideoView的Surface还没有初始化好 你就想要进行播放 具体解决方法google一下就有
