### ISSUE TITLE
使用AndroidStudio引入依赖后运行不成功

### ISSUE THREAD

**Issue by JackyChen1996** [CJT2325/CameraView#143]
调用JCameraVIew报错Binary XML file line #0: Binary XML file line #0: Error inflating class com.cjt2325.cameralibrary.JCameraView

**Comment by CJT2325** [comment]
试试下载源码导入吧～gradle好像很多人都依赖不了～

**Comment by JackyChen1996** [comment]
怎么使用源码导入呢 萌新一枚 我把你的项目下载下来了

**Comment by JackyChen1996** [comment]
@CJT2325 求大佬指点
