### ISSUE TITLE
neuxs 5X手机 摄像头上下颠倒问题

### ISSUE THREAD

**Issue by ELEVENEV** [CJT2325/CameraView#151]
大神，测试遇到以下几个问题，
neuxs 5X手机
后置摄像头预览没有问题，但是拍完保存后视频上下颠倒，拍照没有问题；
前置摄像头预览预览上下颠倒，拍完后视频左右镜像，拍照没有左右镜像，就只是上下颠倒；

前后摄像头的切换会使 右上角的闪光灯和前后摄像头图标随着手机的旋转转动会卡死。

**Comment by HeavenWen** [comment]
前置视频左右镜像的问题解决了吗？

**Comment by ELEVENEV** [comment]
这个问题很好解决，百度现在有很多讲解。
