### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by masteryub** [CJT2325/CameraView#157]
在录制视频中按左键那个返回键，返回回到mainActivity之后等那边录制完之后会崩溃

**Comment by masteryub** [comment]
好像在左键执行之前把录制视频停掉就行了，再把返回键禁用
mCaptureLayout.setLeftClickListener(new ClickListener() {
            @Override
            public void onClick() {
                if (leftClickListener != null) {

                    machine.stopRecord(false, 10);

                    leftClickListener.onClick();
                }
            }
        });

**Comment by lzy6** [comment]
多谢
