### ISSUE TITLE
华为进入项目摄像拍照显示区域黑屏，请问如何处理？

### ISSUE THREAD

**Issue by Zhangxd77** [CJT2325/CameraView#16]
刚进入项目，摄像拍照区域显示黑屏。点击开始按钮，项目崩。
从后台应用进程中起开项目的话，才能看见，
请问怎么修改，谢谢~

**Comment by xxxczc** [comment]
我也遇到了这个问题

**Comment by CJT2325** [comment]
最近忙毕业论文，等搞定会重新重构一下代码

**Comment by Zhangxd77** [comment]
这个我解决了，是权限那块写的问题。你自己写一下申请权限什么的就好了。我现在是录制时间过短就崩，这块还没解决

**Comment by WilliamZhao88** [comment]
解决方法见我发布的issue
