### ISSUE TITLE
华为荣耀 PRA AL00X拍摄视频报运行时错误

### ISSUE THREAD

**Issue by Jerry930326** [CJT2325/CameraView#167]
CameraInterface类中的startRecord方法，运行到mediaRecorder.start();时报错。
try {
            mediaRecorder.prepare();
            mediaRecorder.start();
            isRecorder = true;
        } catch (IllegalStateException e) {
            e.printStackTrace();
            Log.i("CJT", "startRecord IllegalStateException");
            if (this.errorLisenter != null) {
                this.errorLisenter.onError();
            }
        } catch (IOException e) {
            e.printStackTrace();
            Log.i("CJT", "startRecord IOException");
            if (this.errorLisenter != null) {
                this.errorLisenter.onError();
            }
        } catch (RuntimeException e) {
            Log.i("CJT", "startRecord RuntimeException");
        }
捕获到"startRecord RuntimeException"，导致isRecorder = true;这一行未运行！

**Comment by xiaobei56** [comment]
在 startRecord 方法：   mCamera.setPreviewCallback(null);方法之前加上   mCamera.stopPreview();
问题应该可以解决了。
