### ISSUE TITLE
解决了两个bug，在这提一下：1录像崩溃 start failed : -19;;  2.拍照返回后提示消失

### ISSUE THREAD

**Issue by xiaobei56** [CJT2325/CameraView#171]
1. 部分机型（机型比较少见）长按录像时程序崩溃。
问题：在CameraInterface.java 类下，，startRecord时  Camera的 preview未关闭，导致 mediarecored.start 失败。“ MediaRecorder: start failed: -19  ”
解决方法： CameraInterface -> startRecord()   在 mCamera.setPreviewCallback(null); 之前 加上 mCamera.stopPreview();
问题解决！！

**Comment by xiaobei56** [comment]
2. 拍照后点击，取消按钮（就是那个 点击拍照，照片预览页，一个取消按钮( 回勾图标)， 一个确认按钮(√图标)），“轻触拍照，长按摄像”提示 消失，不可见。（这个问题不影响使用，算是个交互问题）。
愿意：该提示文字，被设为透明状态，看上去不可见了。
解决办法：点击返回按钮时再加个 渐变动画让其显示：
` btn_cancel.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
                if (typeLisenter != null) {
                    showTipAnimation();
                    typeLisenter.cancel();
                }
                startAlphaAnimation();
            }
        });`

`public void showTipAnimation() {
        if (!isFirst) {
            ObjectAnimator animator_txt_tip = ObjectAnimator.ofFloat(txt_tip, "alpha", 0f, 1f);
            animator_txt_tip.setDuration(500);
            animator_txt_tip.start();
            isFirst = false;
        }
    }`
问题解决。

**Comment by lzy6** [comment]
多谢
