### ISSUE TITLE
拍照结束。选择保存还是删除时。home或者电源键切出去再返回状态消失

### ISSUE THREAD

**Issue by z2045217** [CJT2325/CameraView#176]

**Comment by z2045217** [comment]
录像过程中。home或者电源键切出去再返回状态错误

**Comment by Alvin3225** [comment]
朋友，之所以出现这个问题 ，是因为onpause和onresume中分别调用了jcamera的onpause和onresume，会重置所有的状态，需要重新处理一下，也就是说在拍照结束或者录制结束的时候，需要将当前预览状态记住，别重置

**Comment by z2045217** [comment]
对。需要保存状态。但是不想改了。直接重置初始状态得了。不然会出bug。录音被占用。无法使用录音。

**Comment by LLQQHH** [comment]
兄弟不止是这样，即使你把这两个状态去掉，还是有问题，因为源码里面，重后台切回运用，也会让他变成初始化状态的。

**Comment by z2045217** [comment]
兄弟，不是状态的问题。状态都是小事。切回后台。录音占用。无法再次启动。

**Comment by LLQQHH** [comment]
我说的状态，不止是表明的，而是源码里面，只是重新初始化了，重新回去预览相机。这个时候录音肯定被占用。你是无法去播放已经录制的视频的。

**Comment by z2045217** [comment]
正在拍摄视频的时候。退出后台。再次进入。。你可以尝试下。。

**Comment by LLQQHH** [comment]
您有解决这个问题了，我姐的最好的做法是：如果在录制状态，切回后台就结束录制，这个再切回前台就播放刚才录制的视频！

**Comment by z2045217** [comment]
对啊。。退出后台就结束录音。
