### ISSUE TITLE
18：9屏幕全屏预览时，画面拉伸

### ISSUE THREAD

**Issue by crazy1235** [CJT2325/CameraView#183]
18：9屏幕全屏预览时，画面拉伸

**Comment by dongliang0201** [comment]
这个要做预览和屏幕尺寸的适配，看zxing在全面屏扫码时也会有这样的问题。可以先吧虚拟导航栏显示，变形会没那么严重，微信也是显示虚拟导航栏的。
![image](https://user-images.githubusercontent.com/8383365/39659520-9d53050a-505c-11e8-9d34-fd35644b74f6.png)

**Comment by GoldenCR7** [comment]
我这边试了用18：9的预览没有拉伸；反而用16：9的小米拍拉伸了
