### ISSUE TITLE
录像开始和结束有“滴”声音，怎么取消？谢谢

### ISSUE THREAD

**Issue by Zhangxd77** [CJT2325/CameraView#20]

**Comment by CJT2325** [comment]
我里面有个AudioUtil，我好想忘记调用了，你可以下源码添加进去

**Comment by Zhangxd77** [comment]
AudioUtil.setAudioManage(mContext);是这句吗？我在startRecord（）开始时候调用的，但是没有用

**Comment by CJT2325** [comment]
我之前是在构造函数里面直接调用，你试试看；我最近重新整理了一下代码，等周末再更新上去

**Comment by Zhangxd77** [comment]
方便加一下您的qq吗？我的qq号码是285601517
