### ISSUE TITLE
手机横着拍完照片或录完视频，预览的时候，照片或视频没有旋转过来

### ISSUE THREAD

**Issue by ZSFeng** [CJT2325/CameraView#22]
请问如何在预览的时候也是横着的

**Comment by CJT2325** [comment]
这个还没有实现····

**Comment by ZSFeng** [comment]
要是想实现有什么思路吗？求大神解答，不然横着拍出来的效果不好...

**Comment by CJT2325** [comment]
拍照倒不是很难，不过录视频就可能麻烦很多

**Comment by ZSFeng** [comment]
那拍照能分析下如何做吗？希望以后能实现这个功能

**Comment by CJT2325** [comment]
@ZSFeng 已经添加该功能，拍照和视频后的浏览都会根据手机水平方向进行相应旋转

**Comment by ZSFeng** [comment]
@CJT2325   1.0.2版本，测试demo有几个问题：
1、竖着录像后预览没有之前版本的全屏，好像被压瘪的感觉？
2、前后摄像头切换，视图好像有点变形
3、录像比较模糊的感觉
4、拍照录像后预览，还能点击聚焦

**Comment by ZSFeng** [comment]
@CJT2325 上面有一些问题可能是不同手机适配问题。然后有些手机一按住录像，界面视图就卡住了，但进度条还在走，后台log：
E/MediaPlayer: error (100, 0)
I/CameraFramework: handleMessage: 1
E/CameraFramework: Error 100
放开log：
E/MediaPlayer: Unable to to create media player
W/System.err: java.io.IOException: setDataSourceFD failed.: status=0x80000000
W/System.err:     at android.media.MediaPlayer.setDataSource(Native Method)
W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1032)
W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1011)
W/System.err:     at android.media.MediaPlayer.setDataSource(MediaPlayer.java:974)
W/System.err:     at com.cjt2325.cameralibrary.JCameraView$2$3$1.run(JCameraView.java:281)
W/System.err:     at java.lang.Thread.run(Thread.java:838)

**Comment by CJT2325** [comment]
445263848 Q
