### ISSUE TITLE
建议：添加视频压缩

### ISSUE THREAD

**Issue by ddssingsong** [CJT2325/CameraView#26]
初步测试结果，使用ffmpeg做出和楼主同样的界面，加入视频压缩，视频可缩小一倍以上并画质不变。
但是ffmpeg过大，希望楼主给出一个不需要添加ffmpeg库的视频压缩的方案，

**Comment by CJT2325** [comment]
android除了ffmpeg能压缩视频还有其他库吗？

**Comment by ddssingsong** [comment]
好像没听说过，看来我要考虑的是如何减少ffmpeg库的大小问题了

**Comment by chenguozhi** [comment]
http://blog.csdn.net/qq_25794733/article/details/50887980 ；我也建议作者加一下视频压缩；10秒2M是现在demo的现状，我们加了视频自动对焦等效果后，10秒4M到8M（在vivo x6s机器上）；必须要压缩了，不然上传太慢了。。。
