### ISSUE TITLE
拍照不可以缩放么

### ISSUE THREAD

**Issue by gwokwong** [CJT2325/CameraView#28]

**Comment by CJT2325** [comment]
我代码中有判断，如果手机支持缩放，即mParams.isSupportZoom返回为true的话，录像时候手指上滑会缩放，不支持则没效果

**Comment by gwokwong** [comment]
我是说拍照，不是录制呢

**Comment by CJT2325** [comment]
拍照没有缩放

**Comment by gwokwong** [comment]
怎么改可以缩放呢，能提供下思路么。JCameraView的onTouchEvent，我试了，检测不到MotionEvent.ACTION_POINTER_DOWN

**Comment by CJT2325** [comment]
@guowang1102 我已经添加浏览时候可以进行缩放的功能了，你更新代码试试看
