### ISSUE TITLE
感觉挺不错的

### ISSUE THREAD

**Issue by ddssingsong** [CJT2325/CameraView#29]
只是有一些卡顿的问题，比如拍照的时候按钮先变化，然后等一会图片才显示出来

**Comment by CJT2325** [comment]
嗯，有的逻辑直接在主线程中去处理，所以有些卡顿，至于那个拍照后按钮先弹出只要修改一下那个拍照后结果的回调函数应该就能处理啦

**Comment by ddssingsong** [comment]
感觉真的很不错，楼主从刚开始到现在更新的内容我都看了，值得学习一下

**Comment by ddssingsong** [comment]
楼主我等着你的好消息，等把这个功能再完善一些，我就试试放到项目里，目前还测到一个内存泄露的问题，退出是回调没清空

**Comment by luckerbai** [comment]
好！后续视频压缩下就更好了！^_^

**Comment by CJT2325** [comment]
@luckerbai 掌握了技术后一定加 ！^_^
