### ISSUE TITLE
Demo不知道是不是最新的？手机上面运行拍摄视频会崩溃，为什么不放开下载让大家测？

### ISSUE THREAD

**Issue by luoyushouchai** [CJT2325/CameraView#30]

**Comment by CJT2325** [comment]
Demo是最新的（1.0.4），你报一下你的手机和崩溃的Log

**Comment by luoyushouchai** [comment]
我这边使用两台手机测了一下，打开应用都会有闪屏效果，崩溃现在不复现了......

**Comment by CJT2325** [comment]
不知道你那个崩溃问题是不是和[#27](https://github.com/CJT2325/CameraView/issues/27)这个问题一样，可能是我那个Demo权限获取失败我没处理好的问题

**Comment by CJT2325** [comment]
最近我会修复这个bug，现在没时间。。。

**Comment by luoyushouchai** [comment]
好的，我再看一下
