### ISSUE TITLE
长按录视频时，如果手指滑出原型按钮，程序崩溃

### ISSUE THREAD

**Issue by lamuTree** [CJT2325/CameraView#31]

**Comment by CJT2325** [comment]
那应该是缩放的问题，你报下你手机型号和崩溃的LOG

**Comment by lamuTree** [comment]
我没有进行缩放操作，只是把手指滑出去了，这个问题应该普遍存在的，我在三星和小米手机上都发现了

**Comment by CJT2325** [comment]
加一下QQ445263848我把刚刚改了的apk发给你试试看，或者我现在更新上去，因为滑动出去这个事件就只触发了缩放这个事件，所以应该是我在处理缩放功能有点问题
