### ISSUE TITLE
三星前置镜头预览异常，拍照奔溃

### ISSUE THREAD

**Issue by AMQR** [CJT2325/CameraView#32]
三星的部分手机，比如去年的A系列SM-A7108，切换为前置摄像头的会导致预览之后大概一半。
然后这时候拍照，会奔溃。报  “y + height must be <= bitmap.height()”

具体位置为 com/yue/customcamera/activity/CameraActivity.java:440
也就是            saveBitmap = Bitmap.createBitmap(saveBitmap, 0, 0, screenWidth, screenWidth * 4/3);这行代码
应该就是首先预览比例和实际比例不符导致的

**Comment by CJT2325** [comment]
好的

**Comment by CJT2325** [comment]
这份代码不是我项目里的代码，但我了解你的意思，加一下qq445263848
