### ISSUE TITLE
强制横屏录制

### ISSUE THREAD

**Issue by sabobo** [CJT2325/CameraView#33]
强制横屏录制，相机预览画面不正常

**Comment by CJT2325** [comment]
我这个不支持横屏录制，所以最好设置一下禁止切换横屏

**Comment by sabobo** [comment]
好的 如果要做的话，有没有好的建议. 我看录制到播放是没问题的 只是预览画面不对,测试

**Comment by CJT2325** [comment]
这个控件能在竖屏的状态下进行横屏录制，但是如果你切换成横屏的话，那些UI控件都会变形，包括分辨率

**Comment by CJT2325** [comment]
445263848
