### ISSUE TITLE
拍照返回问题，能否可以做直接返回，而不是重新显示拍摄按钮后再返回。

### ISSUE THREAD

**Issue by gwokwong** [CJT2325/CameraView#34]
如题。拍照后返回直接销毁本界面，（不重新显示拍照界面）怎么处理。

**Comment by CJT2325** [comment]
可以，你可以加多一个回调接口，在JCameraView里面的 handlerPictureOrVideo方法里面调用就可以了

**Comment by CJT2325** [comment]
不过这样逻辑很奇怪
