### ISSUE TITLE
设置最大录制时间

### ISSUE THREAD

**Issue by powerwolfman** [CJT2325/CameraView#35]
我在camera包中找了半天，感觉就是修改CaptureButton类中的duration，可是不管设置为多少，最后拍下来的视频也就十秒左右，不能再多了，这是不是有点问题？还是说我自己没有找到呢？求解答！！谢谢！！

**Comment by CJT2325** [comment]
JCameraView控件有个属性为duration_max可以设置最长录制时间，不需要到源码里面去修改，直接在布局文件里面设置就可以了

**Comment by powerwolfman** [comment]
嗯，找到了，之前没注意。谢谢啦！！

**Comment by CJT2325** [comment]
觉得好可给个Star 哈。。
