### ISSUE TITLE
相机界面的关闭按钮可以换图标吗

### ISSUE THREAD

**Issue by zhangxiaobin123456** [CJT2325/CameraView#37]
﹀ 可以替换成 × 吗  。
还有如果我依赖了最新的1.0.5的库，会报下面的错
D:\studiocode\Um\recordtest\build\intermediates\res\merged\debug\values-v24\values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:Execution failed for task ':recordtest:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\Android\sdk\build-tools\23.0.3\aapt.exe'' finished with non-zero exit value 1

后边我换了1.0.2的库就没有报这样的错了。是我这边配置的问题吗？

**Comment by CJT2325** [comment]
图片替换不了，不过可以后期我可以添加这个区分，这个图标是绘制出来的；
这些错误应该是资源没找到的异常，我好像都没用到
