### ISSUE TITLE
为什么最新的版本下载下来录制视频没有放大缩小的功能

### ISSUE THREAD

**Issue by startwxx** [CJT2325/CameraView#39]
添加1.0.5依赖也没有缩放效果

**Comment by CJT2325** [comment]
如果没有缩放的话，那应该是该设备Camera不支持缩放功能，所以就没效果

**Comment by startwxx** [comment]
浏览界面能使用两根手指进行缩放也是这个原因么

**Comment by CJT2325** [comment]
你的意思是浏览的时候能用手指缩放吗，而录视频不能缩放这个意思吗？
因为这两个功能都是根据camera是否isSupportZoom返回结果来进行相应的处理的

**Comment by startwxx** [comment]
我的意思是两个都不能，手机是小米5s，相机是支持缩放功能的。而且git上面clone下来的demo和1.0.5依赖代码是一样的么？
好奇怪

**Comment by CJT2325** [comment]
嗯，我明白你的意思，可是自带的API的Caemra在一些手机上就是返回false，这里我也是有点不太清楚。
git上面的代码是最新的代码，应该比1.0.5依赖会更完善一点。

**Comment by startwxx** [comment]
好的谢谢啦，我再看下再向您请教

**Comment by CJT2325** [comment]
不客气，欢迎star :stuck_out_tongue_closed_eyes:
