### ISSUE TITLE
下载的apk打开黑屏

### ISSUE THREAD

**Issue by guanjunhello** [CJT2325/CameraView#41]
下载的demo和我自己集成使用都存在
直接启动app黑屏（权限没问题）
点击前后置切换按钮可以显示画面
或者按Home键再切回来也可以显示画面

手机华为荣耀V8 android7.0

**Comment by CJT2325** [comment]
嗯，应该是我那个Demo的获取权限有点问题，这个问题暂时不是这个控件的原因，有时间我会完善这个Demo获取权限的问题，不好意思

**Comment by guanjunhello** [comment]
应该不是权限的问题吧，我权限都给了，而且我上面有提到，点击前后置切换按钮可以显示画面， 按Home键再切回来也可以显示画面

**Comment by CJT2325** [comment]
恩，不是权限的问题，而是我那个Demo的MainActivity里面处理获取权限的逻辑有点问题，因为我要判断6.0之前和之后分别的处理。
