### ISSUE TITLE
打开黑屏

### ISSUE THREAD

**Issue by LonelyPluto** [CJT2325/CameraView#44]
手机：oppo R9 5.1
把你的权限判断都注释掉了，开始进入还是会黑屏，切换摄像头会变好

**Comment by CJT2325** [comment]
嗯，很多人反映这个问题，初步判断应该是权限的问题，控件本身是没问题的，有时间我去完善一下

**Comment by LonelyPluto** [comment]
@CJT2325 我下载的是你的代码，版本是1.0.4，然后我又直接用的jcenter jar包 是1.0.5  这个没有出现黑屏的现象，方便更新一下你的代码吗

**Comment by CJT2325** [comment]
这上面的版本是最新的哦，是不是你改用jcenter依赖的时候，你的app已经获取到权限了？

**Comment by CJT2325** [comment]
你应该只要在onResume把那行权限判断的语句去掉，这个黑屏的主要原因应该是没有调用到jCameraView.onResume();这行代码，在你切换摄像头的时候，就肯定会调用到，所以切换摄像头就正常了，因为要加那个判断要兼容一下6.0以上要动态获取权限，用户可能不授权，如果不加判断的话则我这个Demo在6.0以上有可能会打开就闪退。 @CodeFarmerZYW

**Comment by LonelyPluto** [comment]
@CJT2325  嗯，非常感谢你的提醒，的确是没有调用到jCameraView.onResume();因为我把权限注释掉了，但是没有注意到granted这个boolean

**Comment by CJT2325** [comment]
嗯，所以这里是我的Demo的不足之处，因为这个动态获取权限我还不是很熟悉，根据我的代码逻辑，有的手机能获取到全部权限，但有的手机却只能获取到一部分权限，所以才导致这个granted为false
