### ISSUE TITLE
切换前置摄像头不好使

### ISSUE THREAD

**Issue by qq634421026** [CJT2325/CameraView#48]
三星A5  android版本4.4
 切换前置摄像头时相机卡住不动 ，再次点击切换 就不卡了 但是还是 后置摄像头

**Comment by CJT2325** [comment]
好的，刚刚也有人反馈这个问题，我魅族却没问题·····心累

**Comment by CJT2325** [comment]
已经修复这个问题，你试试看有没有问题 @qq634421026

**Comment by qq634421026** [comment]
是因为什么原因呢

**Comment by CJT2325** [comment]
mCamera.stopPreview();
//这句要在stopPreview后执行，不然会卡顿或者花屏，之前的问题是顺序反了
 mCamera.setPreviewDisplay(null);

**Comment by qq634421026** [comment]
谢谢了
