### ISSUE TITLE
华为荣耀拍摄视频时设置的setVideoEncodingBitRate没有无效，拍摄出来的视频尺寸很大

### ISSUE THREAD

**Issue by sanwuwy** [CJT2325/CameraView#51]
使用的是华为荣耀PE-CL00(android4.4.2)的手机，发现是设置的mediaRecorder.setVideoEncodingBitRate(1600000);没有生效，拍摄出来的视频尺寸很大，10s钟，内存占用17-25MB，在小米和魅族的手机上，就没有问题，拍出来的视频尺寸比较合理，10s钟，内存占用2.0-3.0MB。

**Comment by CJT2325** [comment]
可以说说你手机分辨率吗

**Comment by sanwuwy** [comment]
![huawei](https://cloud.githubusercontent.com/assets/11894603/26767397/5241e4a0-49d2-11e7-9b2d-c65a9ddff19a.png)
手机的分辨率是1920 * 1080
图片是拍摄的视频的信息
