### ISSUE TITLE
HTC M8（android5.0.2）使用此demo无法自动加载预览（黑屏），必须点击切换摄像头才能使用，锁屏后又变黑屏

### ISSUE THREAD

**Issue by shakespearet** [CJT2325/CameraView#52]

**Comment by CJT2325** [comment]
是下载demo的apk吗？

**Comment by shakespearet** [comment]
下载的apk进去可以预览，但锁屏后又黑屏了，要点切换摄像头才行，我自己做的demo进去的时候就是黑屏，也要点切换摄像头才行

**Comment by CJT2325** [comment]
好，锁屏后黑屏这个我找时间完善，但是启动黑屏这个问题不是我控件的问题，你可以看一下cameraapplication这个model是怎么写的，你模仿一下就可以了。

**Comment by shakespearet** [comment]
好的，谢谢，学习了

**Comment by CJT2325** [comment]
觉得不错欢迎star
