### ISSUE TITLE
下载的demo长按录像直接就结束了，目测一秒都不到

### ISSUE THREAD

**Issue by MichaelMeng666** [CJT2325/CameraView#55]
RT，开始录直接就结束了，怎么破，下载的代码运行的。

**Comment by CJT2325** [comment]
你是直接下载我的demo的apk还是下载代码运行的？？
顺便把log 机型 贴一下

**Comment by MichaelMeng666** [comment]
直接下载apk和运行代码的结果是一样的，手机型号是ZTE V5 MAX，系统版本4.4.4。以下是日志：
![qq 20170608162243](https://user-images.githubusercontent.com/19744045/26919067-f5b4828c-4c66-11e7-84fd-3efb6c344df7.png)
![qq 20170608162254](https://user-images.githubusercontent.com/19744045/26919068-f5d4a724-4c66-11e7-9e18-1d785607ec0f.png)
