### ISSUE TITLE
一加3T代码运行只能长摁录像，不能点击拍照

### ISSUE THREAD

**Issue by zebraoo** [CJT2325/CameraView#56]
一加3T代码运行生成APK只能长摁录像，不能点击拍照。
扫码Demo下载APK，功能正常。

**Comment by CJT2325** [comment]
因为代码我新增了一个可以设置拍照或者录像或者两者都行的api，应该是我设置了只能录像。 @Zerbaoo

**Comment by zebraoo** [comment]
已设置，谢大神

**Comment by CJT2325** [comment]
嗯，欢迎star···
