### ISSUE TITLE
华为荣耀6  安卓4.4版本的录制的视频有19M

### ISSUE THREAD

**Issue by wslja123** [CJT2325/CameraView#58]
华为荣耀6  安卓4.4版本的录制的10秒视频有19M   5.0以上的测试机10s录制都小于2M，这是为什么呢?

**Comment by wslja123** [comment]
我就是用的cameraapplication编译出来的Demo

**Comment by CJT2325** [comment]
华为荣耀有点奇怪·····就华为荣耀这个系列会这样，其它都正常，现在暂时不知道怎么解决，不过试过把比特率设置低一点，视频大小还是能减小，现在的问题就是怎么判断该机是华为荣耀这个系列了···

**Comment by wslja123** [comment]
目前想到的是用android.os.Build.DEVICE得到手机设备的型号
荣耀6 hwH60
荣耀6 plus hwPE
3c  hwH30
3c畅玩版 hwHol
3x hwG750
x1 hw7D 这些是android5.0以前的荣耀热卖机型  目前想到的只有这样判断了。。

**Comment by CJT2325** [comment]
能加一下QQ聊吗 445263848
