### ISSUE TITLE
更改录制框的大小？有没有计划加入这个高度自定义？

### ISSUE THREAD

**Issue by yovenny** [CJT2325/CameraView#60]
![f0c95ee4-dc90-4d6e-8dea-1b497dc10ad1](https://user-images.githubusercontent.com/8280857/27027862-8023d82e-4f95-11e7-857c-b5f53b5ed15b.png)

photoParam.setMargins(0, 0, 0, mCaptureLayout.getCaptureHeight());
 videoViewParam.setMargins(0, 0, 0, mCaptureLayout.getCaptureHeight());
我改了这两个，ui是生效了，但感觉录制的大小还是一样，要改哪些录制参数呀？告诉我呗，

有没有计划加入这个高度自定义？

**Comment by CJT2325** [comment]
那肯定，你要去cameraInterface的startRecorder里面设置分辨率

**Comment by yovenny** [comment]
改完报错，尴尬 
previewSize.height -=mCatureHeight*pictureSize.height/mScreenheigth;
这个分辨率怎么改？@CJT2325 大大

**Comment by CJT2325** [comment]
这个分辨率不能随意设置的，要根据你手机支持的分辨率来设置

**Comment by yovenny** [comment]
具体代码我应该怎么写，就录制视频后获取某一帧作为封面，它的的高度怎么还是为1280，换算后高度肯定不是1280，那这个值具体代码应该减去这个值怎么算？@CJT2325

**Comment by yovenny** [comment]
具体代码我应该怎么写，就录制视频后获取某一帧作为封面，它的的高度怎么还是为1280，换算后高度肯定不是1280，那这个值具体代码应该减去这个值怎么算？@CJT2325

**Comment by CJT2325** [comment]
获取你修改后的长宽比去获取最接近的分辨率，我里面有个类专门获取分辨率的

**Comment by yovenny** [comment]
好

**Comment by yovenny** [comment]
但之前我debug分辨率列表只有size=10,明天继续看看 thanks

**Comment by yovenny** [comment]
谢谢作者

```java
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
        float widthSize = MeasureSpec.getSize(widthMeasureSpec);
        float heightSize = MeasureSpec.getSize(heightMeasureSpec);
        heightSize-=mCaptureLayout.getCaptureHeight();
        screenProp = heightSize / widthSize;
    }
```
