### ISSUE TITLE
魅蓝note2，系统5.1，打开相机失败率很高 ，掉这个方法的时候openCamera(id)，id一直为0，然后就走error了

### ISSUE THREAD

**Issue by strivecheng** [CJT2325/CameraView#65]
失败率大概有80%，就是打开相机失败，直接返回，多试几次，直接就crash了，也看不见log，尴尬。。。

**Comment by CJT2325** [comment]
你是下载我Demo的还是自己运行的？

**Comment by strivecheng** [comment]
我自己的项目gradle添加依赖的，跳转出问题，运行你的demo没有问题，我看了下gradle添加的库和你的demo用的库貌似还是有点区别的。大神，你是不是修改了什么？

**Comment by strivecheng** [comment]
W/CameraBase: An error occurred while connecting to camera: 0
是不是线程的问题，我打断点之后，一步一步走，貌似成功率稍微高点

**Comment by CJT2325** [comment]
嗯 1.1.1这个依赖不是最新的代码，我现在更新一下
