### ISSUE TITLE
最新的库 进去直接崩溃啊

### ISSUE THREAD

**Issue by dongjielitianjiao** [CJT2325/CameraView#66]
我 用的你的demo没有问题，但是用你的最新的库   进去CameraActivity 就直接崩溃了

**Comment by CCTV100** [comment]
兄弟 ，有很多原因可以导致程序崩溃，提问题具体一些，让楼主也好回答你

**Comment by CJT2325** [comment]
刚更新了代码，还有不要运行app那个model   运行cameraApplication这个demo，如果有不清楚的就加群
