### ISSUE TITLE
如何适配单摄像头机型！

### ISSUE THREAD

**Issue by Noah1991** [CJT2325/CameraView#68]
华为荣耀7i机型，单摄像头，系统6.0.1；点击转换摄像头崩溃；
 java.lang.RuntimeException: Camera initialization failed（-19）
应该在转换摄像头时对摄像头个数做个判断；

**Comment by CJT2325** [comment]
嗯，这个我确实没考虑到，我没想到有单摄像头的机型····，这个我到时候添加一个判断上去就能解决了

**Comment by Noah1991** [comment]
还有一个问题，调用AudioUtil来取消录像提示音，没有效果！在JcameraView的构造方法，和开始录像时调用都没用；机型是小米5S

**Comment by CJT2325** [comment]
那个工具类我没使用，因为在7.0以上会报错，暂时还没去处理这个问题
