### ISSUE TITLE
Nexus 5X上使用后置摄像头时画面倒置

### ISSUE THREAD

**Issue by zhangyicoding** [CJT2325/CameraView#69]
Nexus 5X上使用后置摄像头时画面倒置，前置没问题，其它设备华为mate8、红米note3、vivo x9，oppo r9s、魅蓝 metal1都没有问题

**Comment by CJT2325** [comment]
已经处理，但是未更新

**Comment by XiaYongjie** [comment]
@CJT2325 更新了吗

**Comment by CJT2325** [comment]
依赖还没更新

**Comment by XiaYongjie** [comment]
@CJT2325 我看源码了直接用了，谢谢！

**Comment by CJT2325** [comment]
@XiaYongjie 不客气，最近忙 没时间弄这个项目
