### ISSUE TITLE
拍照为什么很模糊

### ISSUE THREAD

**Issue by softsnow** [CJT2325/CameraView#73]
系统相机就比这个清晰的多

**Comment by softsnow** [comment]
我第一次打开不能自动对焦

**Comment by CJT2325** [comment]
嗯···我这个控件第一次打开是没有去自动对焦的·····

**Comment by CJT2325** [comment]
不过我一个对焦的方法，如果你使用源码的话你可以直接调用一下

**Comment by softsnow** [comment]
我设置了有时候也不能对焦成功，我是在cameraHasOpened()方法里设置的，不太对吗还有，我拍完照感觉有个放大的过程，能去掉吗，很抱歉，我刚开始学android，很多看不懂，

**Comment by CJT2325** [comment]
放大可能是分辨率比例没找到最合适的原因，那个第一次自动对焦等我来解决吧

**Comment by softsnow** [comment]
很感谢，抱歉，给您添麻烦了

**Comment by CJT2325** [comment]
@softsnow  新增启动浏览时自动对焦的功能

**Comment by softsnow** [comment]
谢谢，还发现几个问题：1，小米5第一次自动对焦不知道为什么成功率特别低，微信的不会
2，设置视频时长为10s,最终一共是9s,也就是会少一秒
3，录制视频结束，按home键，再切换至前台， 会出现java.lang.RuntimeException: getParameters failed (empty parameters)，是handleFocus方法的  final Camera.Parameters params = mCamera.getParameters();抛出的异常
