### ISSUE TITLE
1.1.3版本 FoucsView 一开始就显示出来了

### ISSUE THREAD

**Issue by yzw1007** [CJT2325/CameraView#74]
1.1.3版本 FoucsView 一开始就显示出来了，1.1.2版本还不存在这个问题。
在JCameraView得onResume方法中，最新的版本是不是把mFoucsView.setVisibility(INVISIBLE);这行放到if (onlyPause) {}这个判断片段里面去了。

**Comment by CJT2325** [comment]
嗯  我刚刚测出来  我现在顺便吧第一次启动对焦也加进去

**Comment by CJT2325** [comment]
@yzw1007 新增启动时自动对焦，同时修复了这个问题
