### ISSUE TITLE
录制视频时向上滑动缩放camera报异常

### ISSUE THREAD

**Issue by yzw1007** [CJT2325/CameraView#77]
java.lang.RuntimeException

setParameters failed

1 android.hardware.Camera.native_setParameters(Native Method)
2 android.hardware.Camera.setParameters(Camera.java:1762)
3 com.cjt2325.cameralibrary.CameraInterface.setZoom(CameraInterface.java:220)
4 com.cjt2325.cameralibrary.JCameraView$2.recordZoom(JCameraView.java:354)
5 com.cjt2325.cameralibrary.CaptureLayout$2.recordZoom(CaptureLayout.java:193)
6 com.cjt2325.cameralibrary.CaptureButton.onTouchEvent(CaptureButton.java:190)
7 android.view.View.dispatchTouchEvent(View.java:7723)

**Comment by CJT2325** [comment]
嗯，我刚修改了一下，可能有些机型缩放会没有反应，你重新更新一下代码
