### ISSUE TITLE
选择只能拍照或只能摄像时，轻触拍照，长按摄像 的提示能否隐藏  

### ISSUE THREAD

**Issue by zmyqucai8** [CJT2325/CameraView#81]
如题。或者只显示轻触拍照 或，长按摄像，
因为使用gradle，没导入源码，
希望作者修改优化一下，谢谢！

**Comment by CJT2325** [comment]
1.1.3这些api都有，我没更新readme，你可以添加依赖，然后跟踪代码看一眼，提示是setTip，只能拍照或着录像这个api我忘记了~~~你看一下
