### ISSUE TITLE
图像渲染的时候被拉伸了

### ISSUE THREAD

**Issue by BaiLuoYan** [CJT2325/CameraView#86]
由于全屏显示，相机成像比例跟屏幕比例不一致导致渲染的时候画面被拉伸了，保存的视频和图片正常，相机成像比例能进行设置吗？

**Comment by CJT2325** [comment]
只能设置SurfaceView的高度了，我默认是全屏的，所以浏览时候也会铺满

**Comment by magiclonw** [comment]
应该是屏幕的支持预览尺寸和图片尺寸选取再优化下，比如平板使用时，你的1000，1200就不科学了

**Comment by CJT2325** [comment]
这个1000是最低限制而已~因为有的机型拿到的最最近屏幕分辨率比的分辨率比较小
