### ISSUE TITLE
oppo R9 明明给了录音权限了，但是还是Toast会提示给点录音权限

### ISSUE THREAD

**Issue by huajieqian** [CJT2325/CameraView#87]
现在测试R9遇到的问题，Android版本是5.0.1的，但是oppo应该自己改了系统，权限在应用时都会询问是否给予权限，然后点了是却还是没法录制视频，会提示”给点录音权限可以?”，去设置里看了录音权限已经是允许了，重新安装下应用就可以了，不知道什么原因

**Comment by CJT2325** [comment]
重构了源码
