### ISSUE TITLE
Can't click the button like "ok" after the camera is finished.

### ISSUE THREAD

**Issue by devzwy** [CJT2325/CameraView#91]
First, thanks to the resources provided by the author.I encountered the following problems when using:
Can't click the button like "ok" after the camera is finished.
It's true to open for the first time.but it won't be available at any time.
and I have a suggestion,I hoped rebuild the project can do performed in the new branch.
Thanks again to the author.

**Comment by CJT2325** [comment]
Use this https://github.com/CJT2325/CameraView/releases
