### ISSUE TITLE
请问这个怎么一进去先自动对焦到中间一下呢?

### ISSUE THREAD

**Issue by shihchieh-ma** [CJT2325/CameraView#95]
我用mate8测试一进去是非常模糊的,必须手点下屏幕才开始对焦,有没有办法先对焦一次呢?我在
onStart()试了下jCameraView.addFocusables(addFocusables,View.FOCUS_FORWARD,View.FOCUSABLES_ALL);
        jCameraView.handlerFoucs(this.getWindowManager().getDefaultDisplay().getWidth(),
                this.getWindowManager().getDefaultDisplay().getHeight());没有用.

**Comment by CJT2325** [comment]
嗯  之前版本有的 我最近重构了大部分代码，所以有的功能还没添加上去，应该最近会持续更新上去的

**Comment by shihchieh-ma** [comment]
这样啊,我就说我在关闭的issues看到有自动对焦的...感谢你的开源!

**Comment by CJT2325** [comment]
嗯  这个功能逻辑已经有了  我完善就可以了， 喜欢就star一个哈~~~

**Comment by shihchieh-ma** [comment]
这么6的必须start啊,那个功能好了麻烦在这回复一下我,我好关闭这个问题哈,

**Comment by shihchieh-ma** [comment]
我今天试着改了一下 把CameraInterface中的doStartPreview里面的focusmode改成FOCUS_MODE_CONTINUOUS_VIDEO就行了,预览自动就对焦了.你之前那个是auto,得手点.
