### ISSUE TITLE
How to get Pass image path or video path to my activity

### ISSUE THREAD

**Issue by VineshChauhan24** [CJT2325/CameraView#99]
first of all I would to thank full to you. I am have problem with get video path and image path captured.
i need first your activity open when my appliction start then successfully record video or captured picture when user click on right mark my next activity with image of video need to open .

how can i get it can you help me?

**Comment by CJT2325** [comment]
```java
jCameraView.setJCameraLisenter(new JCameraListener() {
    @Override
    public void captureSuccess(Bitmap bitmap) {
        Log.i("JCameraView", "bitmap = " + bitmap.getWidth());
    }
    @Override
    public void recordSuccess(String url,Bitmap firstFrame) {
        Log.i("CJT", "url = " + url);
     }
    @Override
    public void quit() {
        MainActivity.this.finish();
    }
});
```

**Comment by VineshChauhan24** [comment]
Thank You
